### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by harshi0102** [Christelle-12/leaderboard#3]
Hi, @Christelle-12  ,Great Job done so far.
Overall, the code appears to be functional and follows some good practices such as using async/await for handling asynchronous operations and encapsulating repeated logic in functions.
 **Required Changes**
 There are few required changes needs to be followed
The code has repetitive code blocks for setting the 'Content-Type' header in the fetch requests. To adhere to the DRY principle, you can consider creating a helper function that takes care of setting common headers, such as 'Content-Type', and reuse it in each fetch request, instead of duplicating the header setting code in multiple places.

``` async function fetchData(url, method, headers, body) {
   const response = await fetch(url, {
    method,
    headers: {
      ...headers,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const data = await response.json();
  return data;
}
```
<img src="https://media2.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

**Comment by bilalrajput09** [comment]
Hi @Christelle-12 , 


## Status : APPROVED 🥳 🥳 

Your project seems great!  There is nothing else to say...

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great UI ✨ 
- Implemented all requirements 👏 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Christelle-12** [comment]
Thank you  for the review I made those changes suggested by @harshi0102
